export const ADD_EVENT_PENDING = 'ADD_EVENT_PENDING'
export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS'
export const ADD_EVENT_ERROR = 'ADD_EVENT_ERROR'

export const GET_SCHEDULE_PENDING = 'GET_SCHEDULE_PENDING'
export const GET_SCHEDULE_SUCCESS = 'GET_SCHEDULE_SUCCESS'
export const GET_SCHEDULE_ERROR = 'GET_SCHEDULE_ERROR'
